spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
#配置.xml文件路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.ktzb.entity


